name = "opencheats"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[vars]
BETTER_AUTH_URL = "https://opencheats.kousaku-maron.workers.dev"

[assets]
binding = "ASSETS"
directory = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "153d37c4e06845809a3810faee5be82d"
preview_id = "153d37c4e06845809a3810faee5be82d"

[[r2_buckets]]
binding = "PLAYGROUND_BUCKET"
bucket_name = "opencheats-playground-media"
